### ISSUE TITLE
[Bug] Test error on account balance history

### ISSUE THREAD

**Issue by benigls** [fivetran/dbt_recurly_source#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I got a unique combination of columns test error in the `stg_recurly__account_balance_history` model. See the log below

```
08:59:37  Failure in test dbt_utils_unique_combination_of_columns_stg_recurly__account_balance_history_account_id__account_updated_at (models/stg_recurly.yml)
08:59:37    Got 142304 results, configured to fail if != 0
08:59:37  
08:59:37    compiled Code at target/compiled/recurly_source/models/stg_recurly.yml/dbt_utils_unique_combination_o_09ddfe5aa4dc88ea9675b6ab28d02754.sql
```

Looking at the package code it seems that it doesn't have heavy data manipulation. So I went straight to the raw data, specifically in the `account_balance_history` table. It seems that the grain of the table is a combination of the `account_id`, `account_updated_at`, and `currency`.

<img width="1158" alt="image 6" src="https://user-images.githubusercontent.com/9935276/222389962-03e1ff11-73d8-4b22-97a9-0e7f6dc6db1e.png">

Query to test the speculation above
<img width="479" alt="image 7" src="https://user-images.githubusercontent.com/9935276/222392163-7b5bc13e-69a8-4a63-b7ce-c878a46c7340.png">

### Expected behavior

The test would be successful

### dbt Project configurations

recurly_database: raw
recurly_schema: recurly

recurly__using_credit_payment_history: false

### Package versions

- package: fivetran/recurly
version: 0.3.0

### What database are you using dbt with?

bigquery

### dbt Version

1.4.3

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by benigls** [comment]
An additional test in the specific model itself

<img width="479" alt="image 7" src="https://user-images.githubusercontent.com/9935276/222394705-24d82166-cd72-4f36-84e3-798d01f679f7.png">

**Comment by benigls** [comment]
In the same test run. I also got this error, and I think it has the same cause

```
08:59:37  Failure in test dbt_utils_unique_combination_of_columns_stg_recurly__plan_currency_history_plan_id__plan_updated_at (models/stg_recurly.yml)
08:59:37    Got 122 results, configured to fail if != 0
08:59:37  
08:59:37    compiled Code at target/compiled/recurly_source/models/stg_recurly.yml/dbt_utils_unique_combination_o_b66fc76034ad86decc08b24f3d65b6c1.sql
```

Test query
<img width="466" alt="image 3" src="https://user-images.githubusercontent.com/9935276/222396180-b1316694-0212-446d-af4e-55b62241e358.png">

**Comment by fivetran-joemarkiewicz** [comment]
HI @benigls thank you for being so active within this package and sharing the errors you are encountering. 

This is really insightful as the data we were developing from only contained one currency. Therefore, we were not able to see that this behavior would occur for the balance history and currency history tables. That being said, I agree with you that this may just be a case of needing to update the tests of these models to include the currency field within the unique combination of columns. See the current test below:

- Balance History
https://github.com/fivetran/dbt_recurly_source/blob/a35f9b1af26d43b615a849a58c055615cf4a1133/models/stg_recurly.yml#L4-L10

- Currency History

https://github.com/fivetran/dbt_recurly_source/blob/a35f9b1af26d43b615a849a58c055615cf4a1133/models/stg_recurly.yml#L542-L548

Your thorough investigation here makes me comfortable that this is the proper path forward to resolving the test error. Additionally since these models do not flow to any downstream transformation models, this shouldn't have any further impact outside of the staging models.

I see you are open to creating a PR. If you would like to, I will happily review and review/merge to incorporate in the next release. As a note, Issue #8 is currently being developed and should be merged by next week. If you open a PR to address this change, we will likely batch the two updates together. Let me know! If not, we are happy to incorporate this fix ourselves.

**Comment by benigls** [comment]
Hi @fivetran-joemarkiewicz, thanks for acknowledging the issue. I'll probably send a PR early next week. Just in case I didn't send a PR by then, feel free to incorporate it yourself. Thanks and I'm looking forward to more developments on the recurly package 🙂

**Comment by fivetran-joemarkiewicz** [comment]
That sounds great @benigls! Next week should be great. We are also keeping a close eye on Issue #8 and will plan to combine these updates alongside those. If that PR is opened sooner, we may make these changes ourselves. If not, we will happily review your PR 😄
